<template>
  <view v-if="record" class="page">
    <view class="notice">演示数据，请勿录入真实顾客信息</view>
    <view class="summary card"><view class="summary-head"><view><text class="name">{{ record.vip1.name }}</text><text class="small">业务单 {{ record.id }}</text></view><text :class="['tag',`tag-${stages[record.status].tone}`]">{{ stages[record.status].label }}</text></view><text class="line">{{ record.businessDate }} {{ record.appointmentTime }} · {{ record.diagnosisType }}</text><text class="line">{{ record.store }} · {{ record.projects?.join('、') || record.estimatedProject }}</text></view>
    <view class="section-title">本次处理</view>
    <view class="card form"><template v-if="record.status==='floorControl'"><picker :range="projectOptions" @change="form.project=projectOptions[$event.detail.value]"><view class="field">建议项目 <text>{{ form.project || '请选择' }}</text></view></picker><textarea v-model="form.note" placeholder="填写场控排诊备注" /></template><template v-else-if="record.status==='arrivalConfirmation'"><picker :range="arrivalOptions" @change="form.result=arrivalOptions[$event.detail.value]"><view class="field">到店结果 <text>{{ form.result }}</text></view></picker><picker mode="time" @change="form.time=$event.detail.value"><view class="field">实际到店时间 <text>{{ form.time || '请选择' }}</text></view></picker><picker :range="['新诊','复诊']" @change="form.diagnosisType=['新诊','复诊'][$event.detail.value]"><view class="field">诊疗类型 <text>{{ form.diagnosisType }}</text></view></picker><textarea v-model="form.note" placeholder="填写到店确认备注" /></template><template v-else-if="record.status==='doctorDiagnosis'"><view class="field readonly">医生 <text>{{ employee.name }}</text></view><picker :range="projectOptions" @change="form.projects=[projectOptions[$event.detail.value]]"><view class="field">服务项目 <text>{{ form.projects?.join('、') || '请选择' }}</text></view></picker><input v-model="form.department" placeholder="项目科室" /><textarea v-model="form.note" placeholder="填写医生排诊备注" /></template><template v-else-if="record.status==='service'"><picker :range="serviceOptions" @change="form.result=serviceOptions[$event.detail.value]"><view class="field">服务结果 <text>{{ form.result }}</text></view></picker><picker :range="projectOptions" @change="form.projects=[projectOptions[$event.detail.value]]"><view class="field">服务项目 <text>{{ form.projects?.join('、') || '请选择' }}</text></view></picker><picker mode="date" @change="form.followupDate=$event.detail.value"><view class="field">回访日期 <text>{{ form.followupDate || '请选择' }}</text></view></picker><textarea v-model="form.note" placeholder="填写服务小结" /><text class="hint">移动端不处理余额、套餐、耗材及业绩扣减。</text></template><template v-else-if="record.status==='followup'"><picker :range="['电话','微信','短信']" @change="form.method=['电话','微信','短信'][$event.detail.value]"><view class="field">回访方式 <text>{{ form.method }}</text></view></picker><picker :range="followupResults" @change="form.result=followupResults[$event.detail.value]"><view class="field">回访结果 <text>{{ form.result }}</text></view></picker><picker mode="date" @change="form.nextDate=$event.detail.value"><view class="field">再次跟进日期 <text>{{ form.nextDate || '无' }}</text></view></picker><textarea v-model="form.note" placeholder="填写回访记录" /></template><button class="primary-btn submit" @tap="submit">完成{{ stages[record.status].label }}</button></view>
    <view class="section-title">顾客与业务信息</view><view class="card details"><view><text>VIP1</text><b>{{ record.vip1.name }} {{ mask(record.vip1.phone) }}</b></view><view v-if="record.vip2"><text>VIP2</text><b>{{ record.vip2.name }} {{ mask(record.vip2.phone) }}</b></view><view><text>人员归属</text><b>{{ staff }}</b></view></view>
    <view class="section-title">流程时间轴</view><view class="card timeline"><view v-for="item in [...record.logs].reverse()" :key="item.id" class="log"><i></i><view><b>{{ item.action }}</b><text>{{ item.time }} · {{ item.operator }}</text><text>{{ item.detail }}</text></view></view></view>
    <button class="customer-link" @tap="openCustomer">查看顾客档案</button>
  </view>
</template>
<script setup>
import { ref, computed } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { getData, getSession, projects, stages, submitStage } from '../../services/repository'
const record = ref(null), employee = ref(null), form = ref({}), projectOptions = projects, arrivalOptions=['已到店','未到店','申请改期'], serviceOptions=['服务已结束','服务中止'], followupResults=['满意','基本满意','需再次跟进','投诉待处理']
const staff = computed(()=>record.value ? Object.entries(record.value.assignments).map(([,name])=>name).filter(Boolean).join('、') : '')
onLoad(query=>{ employee.value=getSession(); const data=getData(); record.value=data.records.find(r=>r.id===query.id); if(!employee.value||!record.value) uni.reLaunch({url:'/pages/login/index'}); form.value=defaults(record.value) })
function defaults(item){ return { project:item.estimatedProject, result:item.status==='arrivalConfirmation'?'已到店':item.status==='service'?'服务已结束':item.status==='followup'?'满意':'', time:item.appointmentTime, diagnosisType:item.diagnosisType, projects:item.projects||[], department:item.department||'', followupDate:item.followupDate||new Date().toISOString().slice(0,10), method:'电话', nextDate:'', note:'' } }
function mask(v){return v.replace(/^(\d{3})\d{4}(\d{4})$/, '$1****$2')} function openCustomer(){uni.navigateTo({url:`/pages/customer-detail/index?id=${record.value.customerId}`})}
function submit(){ try { const updated=submitStage(record.value.id,employee.value,form.value); uni.showToast({title:updated.status===record.value.status?'已登记':'处理成功',icon:'success'}); record.value=updated; form.value=defaults(updated) } catch(e){ uni.showToast({title:e.message||'处理失败',icon:'none'}) } }
</script>
<style scoped>
.summary,.form,.details,.timeline{padding:24rpx}.summary-head{display:flex;justify-content:space-between}.name{display:block;font-size:35rpx;font-weight:700}.small{display:block;margin-top:8rpx;color:#8a94a5;font-size:22rpx}.line{display:block;margin-top:14rpx;color:#586174;font-size:25rpx}.form{padding-bottom:24rpx}.field,input,textarea{display:block;box-sizing:border-box;width:100%;padding:22rpx 0;border-bottom:1rpx solid #edf0f5;font-size:27rpx}.field text{float:right;color:#667085}.readonly{color:#667085}textarea{min-height:150rpx;border:0}.hint{display:block;margin-top:8rpx;color:#9a6700;font-size:22rpx}.submit{margin-top:16rpx;height:78rpx;line-height:78rpx}.details view{display:flex;padding:16rpx 0;border-bottom:1rpx solid #edf0f5;font-size:25rpx}.details view:last-child{border:0}.details text{width:150rpx;color:#7b8494}.details b{flex:1;font-weight:500}.log{display:flex;gap:16rpx;padding:6rpx 0 24rpx}.log i{display:block;width:16rpx;height:16rpx;margin-top:8rpx;border-radius:50%;background:#2167e8;flex:none}.log b,.log text{display:block}.log b{font-size:26rpx}.log text{margin-top:7rpx;color:#7b8494;font-size:22rpx}.customer-link{margin:28rpx 0;background:none;color:#2167e8;font-size:26rpx}
</style>
